name: xmSports

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 10 * * *'
  watch:
    types: started
  repository_dispatch:
    types: xmSports

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
    - uses: actions/checkout@v2
    - name: 'Set up Python'
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: 'Install requirements'
      run: |
        pip install requests
        sckey='${{ secrets.SCKEY }}'
        user='${{ secrets.USER }}'
        pwd='${{ secrets.PWD }}'
        step='${{ secrets.STEP }}'
    - name: '运行【小米运动自动刷步数】'
      run: |
        python3 main.py <<EOF
        ${sckey}
        ${user}
        ${pwd}
        ${step}
        EOF
